---
- name: Provision Slave Nodes
  hosts: jms-slaves
  remote_user: root

  tasks:
  - name: Set Hostname
    ansible.builtin.shell: 'hostnamectl set-hostname {{ inventory_hostname }}'
  
  - name: Stop, Disable Firewall
    ansible.builtin.shell: systemctl stop firewalld && systemctl disable firewalld
  
  - name: Install NFS, iSCSI, etc
    ansible.builtin.yum:
      name:
        - nfs-utils
        - cryptsetup
        - iscsi-initiator-utils
        - git
        - tar
      state: latest
  
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  - name: Install RKE2 Agent
    ansible.builtin.shell: |
      mkdir -p /etc/rancher/rke2
      echo "token: jmsR0cks" > /etc/rancher/rke2/config.yaml
      echo "server: https://10.0.100.10:9345" >> /etc/rancher/rke2/config.yaml
      curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh -
      systemctl enable rke2-agent.service
      systemctl start rke2-agent.service

