---
- name: Provision Master Node
  hosts: jms-master
  remote_user: root

  tasks:
  - name: Set Hostname
    ansible.builtin.shell: 'hostnamectl set-hostname {{ inventory_hostname }}'
  
  - name: Stop, Disable Firewall
    ansible.builtin.shell: systemctl stop firewalld && systemctl disable firewalld
  
  - name: Install NFS, iSCSI, etc
    ansible.builtin.yum:
      name:
        - nfs-utils
        - cryptsetup
        - iscsi-initiator-utils
        - git
        - tar
      state: latest
  
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
  
  - name: Install RKE2
    ansible.builtin.shell:
      cmd: |
        mkdir -p /etc/rancher/rke2
        echo "token: jmsR0cks" > /etc/rancher/rke2/config.yaml
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
        systemctl enable rke2-server.service
        systemctl start rke2-server.service
        ln -s $(find /var/lib/rancher/rke2/data/ -name kubectl) /usr/local/bin/kubectl
        echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> ~/.bashrc
        source ~/.bashrc
      creates: /usr/local/bin/kubectl

  - name: Install Rancher
    ansible.builtin.shell:
      cmd: |
        curl -L https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
        helm repo add jetstack https://charts.jetstack.io
        kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.crds.yaml
        helm upgrade -i cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace
        helm upgrade -i rancher rancher-latest/rancher --create-namespace --namespace cattle-system --set hostname={{ inventory_hostname }} --set bootstrapPassword=jmsR0cks --set replicas=1
        mkdir -p /root/.indicator
        touch /root/.indicator/rancher-installed
      creates: /root/.indicator/rancher-installed

  - name: Install Longhorn
    ansible.builtin.shell: |
      helm repo add longhorn https://charts.longhorn.io
      helm repo update
      helm upgrade -i longhorn longhorn/longhorn --namespace longhorn-system --create-namespace

  - name: Install MetalLB
    ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
