version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    volumes:
    - "./data/redis:/data"
    ports:
    - "8001:8001"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"

  
  # JMS

  jms-arena:
    build:
      context: .
      dockerfile: jms-arena/Dockerfile
    volumes:
    - "./jms-base:/work/jms-base"
    - "./jms-macros:/work/jms-macros"
    - "./jms-arena:/work/jms-arena"
    command: /bin/sh -c "while sleep 1000; do :; done"