apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: unifi
  selector:
    matchLabels:
      {{- include "unifi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "unifi.labels" . | nindent 8 }}
    spec:
      containers:
      - name: unifi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
          - name: stun
            containerPort: 3478
            protocol: UDP
          - name: discovery
            containerPort: 10001
            protocol: UDP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        env:
          - name: MONGO_USER
            value: unifi
          - name: MONGO_PASS
            value: unifi
          - name: MONGO_HOST
            value: mongodb
          - name: MONGO_DBNAME
            value: unifi
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_TLS
            value: "false"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: config
          mountPath: /config
      volumes:
      - name: tz-config
        hostPath:
          path: /etc/localtime
          type: File
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "unifi.fullname" . }}
