{{- $subdict := dict "name" "ui" "valspec" .Values.ui -}}
{{- $dict := merge $subdict . -}}

{{- if $dict.valspec.enabled -}}
{{ template "jms.deployment" $dict }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jms.tpl.name" $dict }}
  labels:
    app: {{ include "jms.tpl.name" $dict }}
    chart: {{ include "jms.chart" $dict }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: {{ include "jms.tpl.name" $dict }}
    release: {{ .Release.Name | quote }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jms.tpl.name" $dict }}-ingress
  labels:
    app: {{ include "jms.tpl.name" $dict }}
    chart: {{ include "jms.chart" $dict }}
    release: {{ .Release.Name | quote }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "jms.tpl.name" $dict }}
            port:
              number: 80
{{- end -}}
