{{- $subdict := dict "name" "electronics" "valspec" .Values.electronics -}}
{{- $dict := merge $subdict . -}}

{{- if $dict.valspec.enabled -}}
{{ template "jms.statefulset" $dict }}
{{- end -}}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ include "jms.tpl.name" $dict }}
  labels:
    app: {{ include "jms.tpl.name" $dict }}
    chart: {{ include "jms.chart" $dict }}
    release: {{ .Release.Name | quote }}
spec:
  config: '{
      "cniVersion": "1.1.0",
      "type": "jms-cni",
      "ip": "10.0.100.6/24"
    }'
{{- end -}}
