apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: jms-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.100.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: jms-advertisement
  namespace: metallb-system