# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/nodes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/nodes.proto", :syntax => :proto3) do
    add_message "jms.electronics.Lights" do
      oneof :mode do
        optional :off, :message, 1, "jms.electronics.Lights.Off"
        optional :constant, :message, 2, "jms.electronics.Lights.Constant"
        optional :pulse, :message, 3, "jms.electronics.Lights.Pulse"
        optional :chase, :message, 4, "jms.electronics.Lights.Chase"
        optional :rainbow, :message, 5, "jms.electronics.Lights.Rainbow"
      end
    end
    add_message "jms.electronics.Lights.Off" do
      optional :off, :bool, 1
    end
    add_message "jms.electronics.Lights.Constant" do
      optional :rgb, :bytes, 1
    end
    add_message "jms.electronics.Lights.Pulse" do
      optional :rgb, :bytes, 1
      optional :speed, :uint32, 2
    end
    add_message "jms.electronics.Lights.Chase" do
      optional :rgb, :bytes, 1
      optional :speed, :uint32, 2
    end
    add_message "jms.electronics.Lights.Rainbow" do
      optional :speed, :uint32, 1
    end
    add_message "jms.electronics.UpdateNode2Field" do
      optional :ipv4, :bytes, 1
      optional :role, :enum, 2, "jms.electronics.NodeRole"
      oneof :data do
        optional :nodata, :message, 3, "jms.electronics.UpdateNode2Field.NoData"
        optional :alliance, :message, 4, "jms.electronics.UpdateNode2Field.Alliance"
        optional :scoringTable, :message, 5, "jms.electronics.UpdateNode2Field.ScoringTable"
      end
    end
    add_message "jms.electronics.UpdateNode2Field.NoData" do
    end
    add_message "jms.electronics.UpdateNode2Field.Alliance" do
      optional :estop1, :bool, 1
      optional :estop2, :bool, 2
      optional :estop3, :bool, 3
    end
    add_message "jms.electronics.UpdateNode2Field.ScoringTable" do
      optional :abort, :bool, 1
    end
    add_message "jms.electronics.UpdateField2Node" do
      optional :role, :enum, 1, "jms.electronics.NodeRole"
      oneof :data do
        optional :nodata, :message, 2, "jms.electronics.UpdateField2Node.NoData"
        optional :alliance, :message, 3, "jms.electronics.UpdateField2Node.Alliance"
        optional :scoringTable, :message, 4, "jms.electronics.UpdateField2Node.ScoringTable"
        optional :shieldGenerator, :message, 5, "jms.electronics.UpdateField2Node.ShieldGenerator"
      end
    end
    add_message "jms.electronics.UpdateField2Node.NoData" do
    end
    add_message "jms.electronics.UpdateField2Node.Alliance" do
      optional :lights1, :message, 1, "jms.electronics.Lights"
      optional :lights2, :message, 2, "jms.electronics.Lights"
      optional :lights3, :message, 3, "jms.electronics.Lights"
    end
    add_message "jms.electronics.UpdateField2Node.ScoringTable" do
      optional :lights1, :message, 1, "jms.electronics.Lights"
      optional :lights2, :message, 2, "jms.electronics.Lights"
    end
    add_message "jms.electronics.UpdateField2Node.ShieldGenerator" do
      optional :lights1, :message, 1, "jms.electronics.Lights"
      optional :lights2, :message, 2, "jms.electronics.Lights"
    end
    add_enum "jms.electronics.NodeRole" do
      value :NODE_UNASSIGNED, 0
      value :NODE_BLUE, 1
      value :NODE_RED, 2
      value :NODE_SCORING_TABLE, 3
      value :NODE_SHIELD_GEN, 4
    end
  end
end

module Jms
  module Electronics
    Lights = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.Lights").msgclass
    Lights::Off = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.Lights.Off").msgclass
    Lights::Constant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.Lights.Constant").msgclass
    Lights::Pulse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.Lights.Pulse").msgclass
    Lights::Chase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.Lights.Chase").msgclass
    Lights::Rainbow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.Lights.Rainbow").msgclass
    UpdateNode2Field = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateNode2Field").msgclass
    UpdateNode2Field::NoData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateNode2Field.NoData").msgclass
    UpdateNode2Field::Alliance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateNode2Field.Alliance").msgclass
    UpdateNode2Field::ScoringTable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateNode2Field.ScoringTable").msgclass
    UpdateField2Node = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateField2Node").msgclass
    UpdateField2Node::NoData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateField2Node.NoData").msgclass
    UpdateField2Node::Alliance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateField2Node.Alliance").msgclass
    UpdateField2Node::ScoringTable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateField2Node.ScoringTable").msgclass
    UpdateField2Node::ShieldGenerator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.UpdateField2Node.ShieldGenerator").msgclass
    NodeRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jms.electronics.NodeRole").enummodule
  end
end
