M48
; DRILL file {KiCad (6.0.10)} date Sat May  6 14:56:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-06T14:56:49+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.250
%
G90
G05
T1
X191.695Y-65.684
X192.71Y-73.304
X193.725Y-65.684
T2
X108.888Y-66.721
X127.888Y-90.721
T3
X104.14Y-54.61
X104.14Y-115.57
X195.58Y-54.61
X195.58Y-115.57
T4
X113.665Y-109.19
X125.095Y-109.19
T0
M30
