/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "nodes.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jms_electronics_Lights, jms_electronics_Lights, AUTO)


PB_BIND(jms_electronics_Lights_Off, jms_electronics_Lights_Off, AUTO)


PB_BIND(jms_electronics_Lights_Constant, jms_electronics_Lights_Constant, AUTO)


PB_BIND(jms_electronics_Lights_Pulse, jms_electronics_Lights_Pulse, AUTO)


PB_BIND(jms_electronics_Lights_Chase, jms_electronics_Lights_Chase, AUTO)


PB_BIND(jms_electronics_Lights_Rainbow, jms_electronics_Lights_Rainbow, AUTO)


PB_BIND(jms_electronics_UpdateNode2Field, jms_electronics_UpdateNode2Field, AUTO)


PB_BIND(jms_electronics_UpdateNode2Field_NoData, jms_electronics_UpdateNode2Field_NoData, AUTO)


PB_BIND(jms_electronics_UpdateNode2Field_Alliance, jms_electronics_UpdateNode2Field_Alliance, AUTO)


PB_BIND(jms_electronics_UpdateNode2Field_ScoringTable, jms_electronics_UpdateNode2Field_ScoringTable, AUTO)


PB_BIND(jms_electronics_UpdateField2Node, jms_electronics_UpdateField2Node, AUTO)


PB_BIND(jms_electronics_UpdateField2Node_NoData, jms_electronics_UpdateField2Node_NoData, AUTO)


PB_BIND(jms_electronics_UpdateField2Node_Alliance, jms_electronics_UpdateField2Node_Alliance, AUTO)


PB_BIND(jms_electronics_UpdateField2Node_ScoringTable, jms_electronics_UpdateField2Node_ScoringTable, AUTO)


PB_BIND(jms_electronics_UpdateField2Node_ShieldGenerator, jms_electronics_UpdateField2Node_ShieldGenerator, AUTO)




