name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5

    # Stage 1 - Build Docs
    - name: Install Python Deps
      run: |
        pip install -r docs/requirements.txt

    - name: Build Docs
      run: |
        mkdir -p build/docs && sphinx-build -a docs build/docs

    # Stage 2 - Build JMS Docker Images
    - name: Run Docker Build
      run: |
        chmod +x docker-build.sh && ./docker-build.sh

    # Stage 3 - Build Installer ISO
    - name: Build ISO
      run: |
        chmod +x docker-build-provision.sh && chmod +x ./provision/build.sh && ./docker-build-provision.sh

    # Stage 4 - Upload Artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: JMS Installer
        path: build/iso

    - uses: actions/upload-artifact@v3
      with:
        name: JMS-Docker-Images
        path: build/docker-images

    # Stage 5 - Upload Docs to gh-pages (if on master)
    - name: Deploy Docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs
        force_orphan: true

    # Stage 6 - Upload ISO to GitHub Releases (if on tag)
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: github.repository_owner == 'GrappleRobotics' && startsWith(github.ref, 'refs/tags/v')
      with:
        files: build/iso